# # Instance Profile variables

# variable "create_profile" {
#   description = "If true, new IAM role and instance profile will be created"
#   type        = string
#   default     = false
# }

# variable "default_instance_role_name" {
#   description = "Name of the default EC2 instance role"
#   type        = string
#   default     = "default_ec2_instance_role2"
# }

variable "aws_iam_instance_profile" {
  description = "Name of the default EC2 instance profile"
  type        = string
  default     = "default_ec2_instance_profile2"
}
# variable "name" {
#   description = "(Optional, Forces new resource) Name of the instance profile."
#   type        = string
# }
# variable "name_prefix" {
#   description = "(Optional, Forces new resource) Creates a unique name beginning with the specified prefix."
#   type        = string
# }

# variable "path" {
#   description = "(Optional, default "/") Path to the instance profile."
#   type        = string
#   default     = "/"
# }

variable "description" {
  description = "The description of the IAM Role."
  type        = string
  default     = "This IAM Role generated by Terraform."
}
variable "role_name" {
  description = "(Optional) Name of the role to add to the profile"
  type        = string
}